"""category added to pitch class, table removed

Revision ID: 15e2cc93c602
Revises: 4ed3e7f53099
Create Date: 2018-09-10 10:22:43.995052

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '15e2cc93c602'
down_revision = '4ed3e7f53099'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('categories')
    op.add_column('comments', sa.Column('pitch_comment', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'comments', 'pitches', ['pitch_comment'], ['id'])
    op.add_column('pitches', sa.Column('category', sa.String(length=255), nullable=True))
    op.add_column('pitches', sa.Column('poster', sa.Integer(), nullable=True))
    op.add_column('pitches', sa.Column('title', sa.String(length=255), nullable=True))
    op.drop_constraint('pitches_the_comment_fkey', 'pitches', type_='foreignkey')
    op.create_foreign_key(None, 'pitches', 'users', ['poster'], ['id'])
    op.drop_column('pitches', 'the_comment')
    op.drop_constraint('users_pitch_poster_fkey', 'users', type_='foreignkey')
    op.drop_column('users', 'pitch_poster')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('pitch_poster', sa.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key('users_pitch_poster_fkey', 'users', 'pitches', ['pitch_poster'], ['id'])
    op.add_column('pitches', sa.Column('the_comment', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'pitches', type_='foreignkey')
    op.create_foreign_key('pitches_the_comment_fkey', 'pitches', 'comments', ['the_comment'], ['id'])
    op.drop_column('pitches', 'title')
    op.drop_column('pitches', 'poster')
    op.drop_column('pitches', 'category')
    op.drop_constraint(None, 'comments', type_='foreignkey')
    op.drop_column('comments', 'pitch_comment')
    op.create_table('categories',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('category', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('pitch_cat', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['pitch_cat'], ['pitches.id'], name='categories_pitch_cat_fkey'),
    sa.PrimaryKeyConstraint('id', name='categories_pkey')
    )
    # ### end Alembic commands ###
