"""Initial Migration

Revision ID: 5e1c607d6923
Revises: 15e2cc93c602
Create Date: 2018-09-10 16:28:07.718702

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5e1c607d6923'
down_revision = '15e2cc93c602'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('comments_pitch_comment_fkey', 'comments', type_='foreignkey')
    op.drop_column('comments', 'pitch_comment')
    op.drop_constraint('pitches_poster_fkey', 'pitches', type_='foreignkey')
    op.drop_column('pitches', 'poster')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('pitches', sa.Column('poster', sa.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key('pitches_poster_fkey', 'pitches', 'users', ['poster'], ['id'])
    op.add_column('comments', sa.Column('pitch_comment', sa.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key('comments_pitch_comment_fkey', 'comments', 'pitches', ['pitch_comment'], ['id'])
    # ### end Alembic commands ###
