"""new foreign key added, renamed rows of collumns

Revision ID: 63977d6c32c6
Revises: 
Create Date: 2018-09-08 12:28:31.494322

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '63977d6c32c6'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('comments', sa.Column('comment', sa.String(), nullable=True))
    op.drop_column('comments', 'pitch')
    op.add_column('pitches', sa.Column('posted', sa.DateTime(), nullable=True))
    op.add_column('pitches', sa.Column('the_comment', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'pitches', 'comments', ['the_comment'], ['id'])
    op.add_column('users', sa.Column('pitch_poster', sa.Integer(), nullable=True))
    op.drop_constraint('users_pitch_id_fkey', 'users', type_='foreignkey')
    op.create_foreign_key(None, 'users', 'pitches', ['pitch_poster'], ['id'])
    op.drop_column('users', 'pitch_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('pitch_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'users', type_='foreignkey')
    op.create_foreign_key('users_pitch_id_fkey', 'users', 'pitches', ['pitch_id'], ['id'])
    op.drop_column('users', 'pitch_poster')
    op.drop_constraint(None, 'pitches', type_='foreignkey')
    op.drop_column('pitches', 'the_comment')
    op.drop_column('pitches', 'posted')
    op.add_column('comments', sa.Column('pitch', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_column('comments', 'comment')
    # ### end Alembic commands ###
